classes:
- service.git.client
- system.linux.system.single
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.git
- system.reclass.storage.salt
- system.salt.minion.pki.authority
- system.salt.minion.pki.certificate
- system.sphinx.server.doc.reclass
- system.keystone.client.single
- system.keystone.client.service.ceilometer
- system.keystone.client.service.nova21
- system.mysql.client.single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_compute_multi
- system.reclass.storage.system.openstack_gateway_cluster
- cluster.mk22_hw_lab_dvr
parameters:
  _param:
    reclass_data_repository: "git@github.com:jiribroulik/mk-lab-salt-model.git"
    reclass_data_revision: hw_dvr
    salt_master_environment_repository: "https://github.com/tcpcloud"
    salt_master_environment_revision: master
    reclass_config_master: 10.10.6.5
    single_address: 10.10.6.5
    salt_master_host: 127.0.0.1
    salt_master_base_environment: prd
    salt_minion_ca_host: ${linux:network:fqdn}
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - service.galera.master.cluster
          params:
            mysql_cluster_role: master
            single_address: 10.0.175.53
        openstack_control_node02:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
            single_address: 10.0.175.62
  #      openstack_control_node03:
   #       classes:
    #      - service.galera.slave.cluster
     #     params:
      #     mysql_cluster_role: slave
        openstack_compute_node01:
          params:
            single_address: 10.0.175.51
            gateway: 10.0.174.1
            tenant_address: 172.17.100.51
            external_address: 100.16.0.105
        openstack_compute_node02: 
          params:
            single_address: 10.0.175.55
            gateway: 10.0.174.1
            tenant_address: 172.17.100.55
            external_address: 100.16.0.106
        openstack_gateway_node01:
          params:
            single_address: 10.0.175.41
            external_address: 100.16.0.110
            tenant_address: 172.17.100.41
        openstack_gateway_node02:
          params:
            single_address: 10.0.175.50
            external_address: 100.16.0.50
            tenant_address: 172.17.100.50
